### ISSUE TITLE
Add optional flag `--to` to designate branch we want to merge TO

### ISSUE THREAD

**Issue by aflashyrhetoric** [aflashyrhetoric/backlog-cli#14]
Default is to create a PR to master, but many workflows have PR to `develop` branch and so on.

Allow for following:
`blg pr --to=develop`

**Comment by aflashyrhetoric** [comment]
[FUTURE] Enable 'default home' branch in `config.yaml`. 
OR
[FUTURE] Enable 'default home' branch in `config.yaml` specifically by creating a sites tree:
```yaml
--defaultMergeBranches:
  - siteOne:
    - develop
  - siteTwo:
    - beta
```
